export const teams = [
  {
    name: "Thunderhawks FC",
    image: "team_assets/zues_logo",
    id: "1",
    attack: 90,
    midfield: 76,
    defense: 72,
    foundingYear: 1960,
    // jersey: "#3498db",
    jersey: "/jerseys/jersey_a.png",
    colors: ["red", "black"],
    colorCodes: ["#c90000", "#000000"],
    achievements: [
      "Dominant in the 1980s",
      "Multiple championships",
      "Perennial contender",
    ],
    fanbase: "Storm Legion",
  },
  {
    name: "Phoenix United",
    image: "team_assets/knights_logo",
    id: "2",
    attack: 86,
    midfield: 85,
    defense: 85,
    jersey: "/jerseys/jersey_b.png",

    foundingYear: 1995,
    colors: ["black", "white"],
    colorCodes: ["#000", "#fff"],
    achievements: [
      "Championship in 2007",
      "Rise from lower divisions",
      "Never-say-die attitude",
    ],
    fanbase: "Phoenix Ultras",
  },
  {
    name: "Serpentara FC",
    image: "team_assets/lions_logo",
    id: "3",
    attack: 87,
    midfield: 69,
    defense: 70,
    foundingYear: 1988,
    jersey: "/jerseys/jersey_c.png",

    colors: ["orange", "blue"],
    colorCodes: ["#e65800", "#0036e6"],
    achievements: [
      "League title in third season",
      "Cultural identity connection",
      "Passionate Serpentari fanbase",
    ],
    fanbase: "Serpentari",
  },
  {
    name: "Eagle Crest FC",
    image: "team_assets/eagles_logo",
    id: "4",
    attack: 80,
    midfield: 88,
    defense: 87,
    jersey: "/jerseys/jersey_d.png",

    foundingYear: 1992,
    colors: ["blue", "black"],
    colorCodes: ["#0225b3", "#000000"],
    achievements: ["Balanced Offense and Defense", "Established in 1992"],
    fanbase: "Harvesters",
  },

  {
    name: "Gallop United",
    image: "team_assets/sunrise_logo",
    id: "5",
    attack: 72,
    midfield: 78,
    defense: 86,
    foundingYear: 2000,
    jersey: "/jerseys/jersey_e.png",

    colors: ["purple", "black"],
    colorCodes: ["#3402b3", "#000"],
    achievements: [
      "Speed and Precision",
      "Strategic Teamwork",
      "Founded in 2000",
    ],
    fanbase: "Gallop Nation",
  },
  {
    name: "Harvest Harts FC",
    image: "team_assets/hearts_logo",
    id: "6",
    attack: 75,
    midfield: 86,
    defense: 76,
    foundingYear: 1975,
    jersey: "/jerseys/jersey_f.png",

    colors: ["green", "purple"],
    colorCodes: ["#02b35b", "#4902b3"],
    achievements: [
      "Consistent Playoff Appearances",
      "Strong Aerial Attack Strategy",
      "Established in 1975",
    ],
    fanbase: "Eagle Squadron",
  },
];
